package com.barclay.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.barclay.demo.model.Customer;
import com.barclay.demo.service.BarclayDemoService;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@RestController
@RequestMapping("barclaydemoapi")
@Api(tags="BarclayDemo-Api",description="Demand management apis")
public class BarclayDemoController<T extends Customer> {
	
	@Autowired
    BarclayDemoService<T> service;
	
	@RequestMapping(method= RequestMethod.POST, value="/add")
	@ApiOperation(value = "Save records to database",notes="Id value should not be set for autogenerated value")
	@ApiResponses( value = {
			@ApiResponse(code=200,message="Successfully saved rescords to database"),
			@ApiResponse(code=500,message="Failed to save the record")
	})
	public ResponseEntity<T> add( @ApiParam(value="Model to add", required=true)@Validated @RequestBody  Customer customer,BindingResult result) {
       	ResponseEntity<T> resp=(ResponseEntity<T>) service.insertCustomer(customer);
		return resp;
	}
}
